export DYNFIWRKDIR="."
export SRCCONF=${DYNFIWRKDIR}/dynfi-src.conf
export MAKEOBJDIRPREFIX=${DYNFIWRKDIR}/obj
export KERNCONF=DYNFI

NCPUS=$(sysctl -n hw.ncpu)

FBSD_TREE=${DYNFIWRKDIR}/freebsd
FBSD_BRANCH=dynfi-13
PORT_BRANCH=default

DYNFI_REPO=${DYNFIWRKDIR}/freebsd-base-repo/${FBSD_BRANCH}

date=$(date "+%Y%m%d-%H%M%S")
LOGS_DIR=/tmp/builder_logs_${USER}_${date}
PID_FILE=/tmp/build-${USER}-dynfi.pid

